FROM python:3.9

WORKDIR ./yolov5
 
COPY ./yolov5 .

RUN pip install -r requirements_use.txt
RUN pip install torch==1.10.2+cu102 torchvision==0.11.3+cu102 torchaudio===0.10.2+cu102 -f https://download.pytorch.org/whl/cu102/torch_stable.html
RUN pip install -r requirements.txt
EXPOSE 8088
CMD ["python"]
# RUN apt-get install libgl1-mesa-glx
# CMD ["python", "./main.py"]